# Generated by Django 5.0.4 on 2024-04-10 19:31

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='UploadFiles',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.FileField(upload_to='uploads_model')),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Result',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sport', models.CharField(max_length=255)),
                ('avg_speed', models.FloatField(blank=True, help_text='m/s', null=True)),
                ('timestamp', models.DateTimeField()),
                ('distance', models.FloatField(blank=True, help_text='m', null=True)),
                ('total_calories', models.IntegerField(blank=True, help_text='kcal', null=True)),
                ('avg_heart_rate', models.FloatField(blank=True, help_text='bmp', null=True)),
                ('file_hash', models.CharField(max_length=255)),
                ('fit_file', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='result', to='running.uploadfiles')),
            ],
        ),
    ]
